import type {
  FireStation,
  Hospital,
  Incident,
  RiskArea,
} from "@/lib/disaster-response/types";

export const FIRE_STATIONS: FireStation[] = [
  {
    address: "서울특별시 중구 퇴계로 394",
    id: "fs-jungbu",
    jurisdiction: "중구·종로구 남부",
    latitude: 37.5646,
    longitude: 127.015,
    name: "중부소방서",
    resources: { ambulances: 3, fireEngines: 5, rescueTrucks: 2 },
  },
  {
    address: "서울특별시 종로구 율곡로 78",
    id: "fs-jongno",
    jurisdiction: "종로구",
    latitude: 37.5758,
    longitude: 126.9876,
    name: "종로소방서",
    resources: { ambulances: 2, fireEngines: 4, rescueTrucks: 1 },
  },
  {
    address: "서울특별시 용산구 한강대로 167",
    id: "fs-yongsan",
    jurisdiction: "용산구",
    latitude: 37.5313,
    longitude: 126.9718,
    name: "용산소방서",
    resources: { ambulances: 3, fireEngines: 4, rescueTrucks: 2 },
  },
  {
    address: "서울특별시 강남구 테헤란로 518",
    id: "fs-gangnam",
    jurisdiction: "강남구",
    latitude: 37.5097,
    longitude: 127.063,
    name: "강남소방서",
    resources: { ambulances: 4, fireEngines: 6, rescueTrucks: 2 },
  },
  {
    address: "부산광역시 중구 중앙대로 110",
    id: "fs-busan-jungbu",
    jurisdiction: "부산 중구·동구",
    latitude: 35.1088,
    longitude: 129.0342,
    name: "부산중부소방서",
    resources: { ambulances: 3, fireEngines: 5, rescueTrucks: 2 },
  },
  {
    address: "부산광역시 해운대구 해운대로 1064",
    id: "fs-busan-haeundae",
    jurisdiction: "해운대구·센텀권",
    latitude: 35.1782,
    longitude: 129.1704,
    name: "해운대소방서",
    resources: { ambulances: 3, fireEngines: 5, rescueTrucks: 2 },
  },
];

export const HOSPITALS: Hospital[] = [
  {
    address: "서울특별시 종로구 대학로 101",
    emergencyRoom: true,
    id: "h-seoul-national",
    latitude: 37.5796,
    longitude: 126.9989,
    name: "서울대학교병원",
    phone: "02-2072-2114",
    specialties: ["응급의학", "외상", "화상", "심혈관", "소아"],
  },
  {
    address: "서울특별시 중구 을지로 245",
    emergencyRoom: true,
    id: "h-nmc",
    latitude: 37.5672,
    longitude: 127.0057,
    name: "국립중앙의료원",
    phone: "02-2260-7114",
    specialties: ["응급의학", "외상", "감염", "중환자"],
  },
  {
    address: "서울특별시 용산구 대사관로 59",
    emergencyRoom: true,
    id: "h-soonchunhyang",
    latitude: 37.5338,
    longitude: 127.0045,
    name: "순천향대학교 서울병원",
    phone: "02-709-9114",
    specialties: ["응급의학", "내과", "외상", "정형외과"],
  },
  {
    address: "서울특별시 강남구 일원로 81",
    emergencyRoom: true,
    id: "h-samsung",
    latitude: 37.4883,
    longitude: 127.0855,
    name: "삼성서울병원",
    phone: "02-3410-2114",
    specialties: ["응급의학", "심혈관", "외상", "소아", "중환자"],
  },
  {
    address: "부산광역시 서구 구덕로 179",
    emergencyRoom: true,
    id: "h-busan-national",
    latitude: 35.1019,
    longitude: 129.0193,
    name: "부산대학교병원",
    phone: "051-240-7000",
    specialties: ["응급의학", "외상", "화상", "중환자"],
  },
  {
    address: "부산광역시 해운대구 해운대로 875",
    emergencyRoom: true,
    id: "h-inje-haeundae",
    latitude: 35.1736,
    longitude: 129.1824,
    name: "인제대학교 해운대백병원",
    phone: "051-797-0100",
    specialties: ["응급의학", "외상", "심혈관", "정형외과"],
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    address: "서울특별시 중구 세종대로 110",
    createdAt: "2026-06-11T00:30:00.000Z",
    description: "시청 인근 지하 보행로 연기 신고. 현장 접근로 확인 필요.",
    id: "inc-001",
    latitude: 37.5665,
    longitude: 126.978,
    occurredAt: "2026-06-11T05:10:00.000Z",
    riskLevel: "high",
    status: "reported",
    title: "시청역 연기 감지 신고",
    type: "fire",
  },
  {
    address: "서울특별시 용산구 이태원로 177",
    createdAt: "2026-06-11T01:00:00.000Z",
    description: "보행자 낙상 및 구급 요청. 야간 유동 인구 밀집.",
    id: "inc-002",
    latitude: 37.5345,
    longitude: 126.9947,
    occurredAt: "2026-06-11T06:20:00.000Z",
    riskLevel: "medium",
    status: "dispatched",
    title: "이태원 보행자 구급 요청",
    type: "medical",
  },
];

export const BASE_RISK_AREAS: RiskArea[] = [
  {
    baseScore: 58,
    factors: ["업무시설 밀집", "출퇴근 유동 인구"],
    id: "risk-jongno-jung",
    latitude: 37.5704,
    longitude: 126.9827,
    name: "종로·중구 도심권",
    recentIncidentCount: 0,
    riskLevel: "medium",
    riskScore: 58,
  },
  {
    baseScore: 44,
    factors: ["관광 상권", "야간 보행 수요"],
    id: "risk-yongsan",
    latitude: 37.5346,
    longitude: 126.993,
    name: "용산·이태원권",
    recentIncidentCount: 0,
    riskLevel: "medium",
    riskScore: 44,
  },
  {
    baseScore: 67,
    factors: ["고층 업무시설", "교통량 높음"],
    id: "risk-gangnam",
    latitude: 37.5013,
    longitude: 127.0396,
    name: "강남 업무권",
    recentIncidentCount: 0,
    riskLevel: "high",
    riskScore: 67,
  },
  {
    baseScore: 31,
    factors: ["주거지역", "상대적으로 낮은 주간 밀도"],
    id: "risk-mapo",
    latitude: 37.5568,
    longitude: 126.9236,
    name: "마포 서부권",
    recentIncidentCount: 0,
    riskLevel: "low",
    riskScore: 31,
  },
  {
    baseScore: 55,
    factors: ["항만·철도 교통 결절점", "관광·상업시설 밀집"],
    id: "risk-busan-central",
    latitude: 35.1152,
    longitude: 129.0411,
    name: "부산역·중구 도심권",
    recentIncidentCount: 0,
    riskLevel: "medium",
    riskScore: 55,
  },
  {
    baseScore: 60,
    factors: ["대형 전시장", "해운대 관광 수요"],
    id: "risk-busan-haeundae",
    latitude: 35.1695,
    longitude: 129.1366,
    name: "부산 해운대·센텀권",
    recentIncidentCount: 0,
    riskLevel: "medium",
    riskScore: 60,
  },
];
